company:
  name: "GitLab"
  subreddits:
    - "gitlab"
    - "devops"
    - "git"
    - "programming"
    - "kubernetes"
    - "selfhosted"
    - "cicd"
  keywords:
    - "GitLab"
    - "CI/CD"
    - "DevOps"
    - "merge request"
    - "pipeline"
    - "runner"
    - "repository"
    - "self-managed"
    - "omnibus"
    - "gitaly"
    - "SAML"
    - "kubernetes"
    - "helm"
    - "docker"
    - "postgresql"
    - "redis"
    - "nginx"
    - "sidekiq"
  response_tone: "professional, technical, helpful"
  #docs_sitemap: "https://handbook.gitlab.com/sitemap.xml"         # Path to the XML sitemap for docs.gitlab.com
  together_api_key: "tgp_v1_8399z3vIHMco_8fnoClMO3HrY5X7c2CU_H4SmKU5Azk"  # API key for Together.ai
  #docs_url: "https://handbook.gitlab.com/handbook/"
  
reddit:
  client_id: "qtYFFTMpwiVsLebMyZJR7g"
  client_secret: "uAJgMhu95Y5PRlFwRx_z6T_FoRU9AA"
  user_agent: "GitLabEngagementBot/0.1"
  days_back: 10
  
slack:
  webhook_url: "https://hooks.slack.com/services/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"  # Replace with your actual Slack webhook URL
  workflow_webhook_url: "https://hooks.slack.com/triggers/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"  # Slack workflow webhook URL
  
topic_modeling:
  num_topics: 10
  passes: 20
  random_state: 42

