company:
  name: "GitLab"
  subreddits:
    - "gitlab"
    - "devops"
    - "git"
    - "programming"
    - "kubernetes"
    - "selfhosted"
    - "cicd"
  keywords:
    - "GitLab"
    - "CI/CD"
    - "DevOps"
    - "merge request"
    - "pipeline"
    - "runner"
    - "repository"
    - "self-managed"
    - "omnibus"
    - "gitaly"
    - "SAML"
    - "kubernetes"
    - "helm"
    - "docker"
    - "postgresql"
    - "redis"
    - "nginx"
    - "sidekiq"
  response_tone: "professional, technical, helpful"
  docs_sitemap: "https://docs.gitlab.com/sitemap.xml"         # Path to the XML sitemap for docs.gitlab.com
  together_api_key: "tgp_v1_z1ZvF7xdQG2W1XJWKTfYaB8_io0rTG3T2d-jJuJUoP4"  # API key for Together.ai
  docs_url: "https://docs.gitlab.com"
  
reddit:
  client_id: "qtYFFTMpwiVsLebMyZJR7g"
  client_secret: "uAJgMhu95Y5PRlFwRx_z6T_FoRU9AA"
  user_agent: "GitLabEngagementBot/0.1"
  days_back: 7
  
topic_modeling:
  num_topics: 5
  passes: 10
  random_state: 42

